language: node_js

node_js:
  - '5'

env:
  global:
    - NODE_ENV=CI

cache:
  directories:
    - node_modules

git:
  depth: 100

script:
  - make setup
  - make check
  - make lint
  - make test
  - NODE_ENV=production make package
